CREATE TABLE IF NOT EXISTS fp_ticket_imports (
    id CHAR(36) NOT NULL,
    event_id CHAR(36) NOT NULL,
    ticket_type_id CHAR(36) NULL,
    batch_id CHAR(36) NULL,
    file_name VARCHAR(255) NOT NULL,
    file_hash CHAR(64) NOT NULL,
    col_separator CHAR(4) NOT NULL DEFAULT ',',
    col_code INT NOT NULL DEFAULT 0,
    col_external_id INT NULL,
    col_max_entries INT NULL,
    default_max_entries INT NOT NULL DEFAULT 1,
    import_mode VARCHAR(30) NOT NULL DEFAULT 'ADICIONAR_ATUALIZAR',
    import_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    total_rows INT NOT NULL DEFAULT 0,
    processed INT NOT NULL DEFAULT 0,
    inserted INT NOT NULL DEFAULT 0,
    updated INT NOT NULL DEFAULT 0,
    skipped INT NOT NULL DEFAULT 0,
    errors INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1000) NULL,
    created_by CHAR(36) NULL,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY ix_fp_ticket_imports_event (event_id, created_at),
    CONSTRAINT fk_fp_ticket_imports_event FOREIGN KEY (event_id) REFERENCES fp_events (id),
    CONSTRAINT fk_fp_ticket_imports_type FOREIGN KEY (ticket_type_id) REFERENCES fp_ticket_types (id),
    CONSTRAINT fk_fp_ticket_imports_batch FOREIGN KEY (batch_id) REFERENCES fp_ticket_batches (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fp_ticket_import_rows (
    id CHAR(36) NOT NULL,
    import_id CHAR(36) NOT NULL,
    import_row_number INT NOT NULL,
    ticket_code VARCHAR(160) NOT NULL,
    external_id VARCHAR(160) NULL,
    max_entries INT NOT NULL DEFAULT 1,
    row_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    error_detail VARCHAR(500) NULL,
    ticket_id CHAR(36) NULL,
    PRIMARY KEY (id),
    KEY ix_fp_ticket_import_rows_import (import_id, import_row_number),
    CONSTRAINT fk_fp_ticket_import_rows_import FOREIGN KEY (import_id) REFERENCES fp_ticket_imports (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
