<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FastPass.Application\FastPass.Application.csproj" />
    <ProjectReference Include="..\FastPass.Infrastructure\FastPass.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <UserSecretsId>FastPass.Api-Development</UserSecretsId>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
